name: Buid, Test and Deploy

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      isOfficialBuild:
        description: On non-official builds we don't burn in a git sha.
        default: false
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/jhfbosman/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:OfficialBuild=${{ github.event.inputs.isOfficialBuild }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create the Nuget package
      run: dotnet pack --configuration Release
    - name: Publish the Nuget package to GPR
      run: dotnet nuget push ./bin/Release/*.nupkg
